#!/bin/bash
ECHO_PREFIX_INFO="\033[1;32;40mINFO...\033[0;0m"
ECHO_PREFIX_ERROR="\033[1;31;40mError...\033[0;0m"


ls -l "/opt/test" > /dev/null
status=$?
if [ $status -ne 0 ];then
    echo -e $ECHO_PREFIX_INFO "target dir not exist" 
fi

if [ ! -d "/opt/test" ]; then
    echo -e $ECHO_PREFIX_INFO "double confirm: target dir not exist" 
fi

exit 0
